#332 オンライン展示関連の実装
afes-website/front pull request #335
Opened 2020-10-01 12:34 UTC by su8ru

close #332 

- [ ] draft
  - [ ] post 
  - [x] list
  - [x] manage
  - [x] accept / reject
  - [ ] publish
  - [ ] follow afes-website/docs#152
- [ ] exhibition
  - [x] list
  - [x] manage (back 405)
  - [ ] visitor view

2020-10-10 05:05 UTC, Takeno-hito requested changes

2020-10-10 07:14 UTC, su8ru commented on src/components/DraftTable.vue
> +      if (this.exh_id) draft.exhibition.id === this.exh_id;
💢 

Array.prototype.filter() - JavaScript | MDN
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2020-10-10 07:14 UTC, su8ru commented on src/components/DraftTable.vue
> +          (draft) => draft.status === "accepted" && !draft.deleted
一度公開して戻ってきたものが含まれるの、嫌では

2020-10-10 07:15 UTC, su8ru commented on src/views/admin/draft/draft_manage.vue
> +        Preview ボタンで確認後、Accept / Reject ボタンでレビューしてください。
して ― して
のほうが気持ち悪いけどな

2020-10-10 07:15 UTC, ibuki2003 commented on src/components/DraftTable.vue
> +      if (this.exh_id) draft.exhibition.id === this.exh_id;
returnし忘れてそう…
ていうかなんでeslintに怒られないんだ

2020-10-10 07:16 UTC, su8ru commented on src/components/DraftTable.vue
> +      if (this.exh_id) draft.exhibition.id === this.exh_id;
あれ？たしかに
なんだこれ

2020-10-10 07:16 UTC, su8ru commented on src/views/admin/draft/draft_manage.vue
> +  accept_draft() {
current のときは disable するか

2020-10-10 07:16 UTC, su8ru commented on src/views/admin/draft/draft_post.vue
> +          指定の draft を取得
そうですね

2020-10-10 07:40 UTC, su8ru commented on src/components/DraftTable.vue
> +      if (this.exh_id) draft.exhibition.id === this.exh_id;
理由が判明、exh_id による絞り込みは上層コンポーネントで既に行なわれていた

DraftTable 上の絞り込み笑を消します

2020-10-10 07:45 UTC, Takeno-hito commented on src/components/DraftTable.vue
> +          (draft) => draft.status === "accepted" && !draft.deleted
別に公開されなくなってもpublishedはtrueのままだけど…

2020-10-10 07:45 UTC, Takeno-hito commented on src/views/admin/draft/draft_manage.vue
> +        Preview ボタンで確認後、Accept / Reject ボタンでレビューしてください。
じゃあした後、でもいい

2020-10-10 07:55 UTC, su8ru commented on src/views/admin/draft/draft_manage.vue
> +        Preview ボタンで確認後、Accept / Reject ボタンでレビューしてください。
した ― して
も大して変わらないという持論

2020-10-10 07:56 UTC, su8ru commented on src/components/DraftTable.vue
> +          (draft) => draft.status === "accepted" && !draft.deleted
なので archived を別でフィルターしています

2020-10-10 07:58 UTC, Takeno-hito commented on src/views/admin/draft/draft_manage.vue
> +        Preview ボタンで確認後、Accept / Reject ボタンでレビューしてください。
ええ、どっちかに変えてほしいな

2020-10-10 07:58 UTC, Takeno-hito commented on src/components/DraftTable.vue
> +          (draft) => draft.status === "accepted" && !draft.deleted
`accepted && !published` なら公開済みのを弾けるけど

2020-10-10 08:05 UTC, su8ru commented on src/components/DraftTable.vue
> +          (draft) => draft.status === "accepted" && !draft.deleted
やりたいことがよくわからないので実装してみて

2020-10-10 08:06 UTC, su8ru commented on src/views/admin/draft/draft_manage.vue
> +        Preview ボタンで確認後、Accept / Reject ボタンでレビューしてください。
し にすれば解決だな

2020-10-11 11:31 UTC, Takeno-hito submitted a review, later dismissed

2020-10-11 12:12 UTC, su8ru reviewed
Approve

Saigo takemura ni mottekareta is totemo kuyasii

2020-10-12 14:54 UTC, Takeno-hito submitted a review, later dismissed

2020-10-14 07:08 UTC, su8ru commented
ふにょーん
ふにゅーん

2020-10-14 12:27 UTC, su8ru commented
admin top がまだでした

2020-10-15 06:38 UTC, Takeno-hito submitted a review, later dismissed

2020-10-15 07:19 UTC, ibuki2003 requested changes
- 文法崩壊は無視しました
- 見た目は全くチェックしてません
- ねむい

2020-10-15 07:19 UTC, ibuki2003 commented on src/components/ExhibitionCard.vue
> +  @Prop({ required: true, default: "" })
どっち

2020-10-15 07:19 UTC, ibuki2003 commented on src/views/admin/blog/manage_path.vue
> +@import "../../../../node_modules/diff2html/bundles/css/diff2html.min.css";
相対パスになってしまった！(かなしい)

2020-10-15 07:19 UTC, ibuki2003 commented on src/views/admin/exh/exh_list.vue
> +<style lang="scss"></style>
消

2020-10-15 07:21 UTC, su8ru commented on src/components/CommentList.vue
> +  draftId?: number;
賢み

2020-10-15 07:21 UTC, su8ru commented on src/App.vue
> +  exhibition_logged_in = false;
そもそもこれ data として UserInfo を持って get を用意するのがきれいな気がしてきたな

2020-10-15 07:56 UTC, su8ru commented on src/components/CommentList.vue
> +    if (markdown) return Markdown.render(markdown);
あーーーまあいいんじゃね（ねむい）

2020-10-15 07:57 UTC, su8ru commented on src/components/ExhibitionCard.vue
> +  @Prop({ required: true, default: "" })
これあちこちにありそう
なんかお気持ち的に default を指定したかったんだけど、確かに指定する意味がないな

2020-10-15 07:57 UTC, su8ru commented on src/views/admin/blog/manage_path.vue
> +@import "../../../../node_modules/diff2html/bundles/css/diff2html.min.css";
ぐえーーーー

2020-10-15 16:37 UTC, su8ru commented
re-req @Takeno-hito @ibuki2003

2020-10-15 22:26 UTC, ibuki2003 approved these changes
changes since last reviewができなくてキレています(viewedチェック使ったから…?)

2020-10-16 00:02 UTC, Takeno-hito approved these changes

2020-10-16 00:03 UTC, merged