#325 ブログ html 対応 & 埋め込み対応
afes-website/front pull request #342
Opened 2020-10-06 14:24 UTC by su8ru

close #325 

こんな Issue だったんだ………知らなかった………

2020-10-06 14:32 UTC, ibuki2003 requested changes

2020-10-06 14:32 UTC, ibuki2003 commented on src/components/EmbedModal.vue
> +  ] as EmbedExample[];
型指定+`as const`のがうれしい

2020-10-06 14:32 UTC, ibuki2003 commented on src/components/EmbedModal.vue
> +        "https://youtu.be/hy6B_EPE50s",
動画サンプルがこれ…

2020-10-06 14:39 UTC, ibuki2003 commented on src/components/EmbedModal.vue
> +    const match = strip_content.match(/^youtu.be\/(\w+)/);
ごめんなサイ
```suggestion
    const match = strip_content.match(/^youtu\.be\/(\w+)/);
```

2020-10-06 14:45 UTC, su8ru commented on src/components/EmbedModal.vue
> +        "https://youtu.be/hy6B_EPE50s",
はい

![image](https://user-images.githubusercontent.com/33474143/95217294-fdd3d180-082d-11eb-9f0e-eee391d3286d.png)

2020-10-06 14:45 UTC, ibuki2003 approved these changes

2020-10-07 00:25 UTC, Takeno-hito approved these changes

2020-10-07 00:36 UTC, ibuki2003 approved these changes

2020-10-07 03:11 UTC, merged