feat: change link to use after fes
afes-website/front pull request #390
Opened 2020-11-02 08:14 UTC by Takeno-hito

2020-11-02 10:54 UTC, ibuki2003 requested changes

2020-11-02 10:54 UTC, ibuki2003 commented on src/views/exhibition/exh_show.vue
> +    <b-alert show="" variant="primary" class="mt-1">
```suggestion
    <b-alert show variant="primary" class="mt-1">
```

2020-11-02 13:13 UTC, Takeno-hito commented on src/views/exhibition/exh_show.vue
> +    <b-alert show="" variant="primary" class="mt-1">
なんかそれeslintかなにかでwarningが出たのよね、後で確認してみます

2020-11-02 13:35 UTC, ibuki2003 approved these changes

2020-11-02 13:35 UTC, merged

2020-11-03 08:16 UTC, su8ru commented on src/views/exhibition/exh_show.vue
> +    <b-alert show="" variant="primary" class="mt-1">
後世のために書いておきますが、PhpStorm です