#387 renderer 周りの修正
afes-website/front pull request #391
Opened 2020-11-03 08:14 UTC by su8ru

fix #387

- fix: use MarkdownRenderer as draft preview renderer
- feat: give  to twttr widgets load

2020-11-03 08:18 UTC, ibuki2003 requested changes

2020-11-03 08:18 UTC, ibuki2003 commented on src/components/MarkdownRenderer.vue
> +2
これはなに
```suggestion
```

2020-11-03 08:18 UTC, ibuki2003 commented on src/components/MarkdownRenderer.vue
> +    <div class="markdown-output" v-html="rendered" ref="mdOut"></div>
unused?
```suggestion
    <div class="markdown-output" v-html="rendered"></div>
```

2020-11-03 08:18 UTC, su8ru commented on src/components/MarkdownRenderer.vue
> +2
なんだこれ…………

2020-11-03 15:27 UTC, ibuki2003 approved these changes

2020-11-04 08:25 UTC, Takeno-hito approved these changes

2020-11-04 09:07 UTC, merged